- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: textvqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_textvqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: ok_vqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_ok_vqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: mmbench
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_mmbench
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: mmmu
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_mmmu
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: chartqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_chartqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: ai2d
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_ai2d
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: mme
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_mme
  output_path: "./logs/"


- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: hallusion_bench
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_hallusion_bench
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: docvqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_docvqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: ocrbench
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_ocrbench
  output_path: "./logs/"
  
- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: gqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_gqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: scienceqa_img
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_scienceqa_img
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: iconqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_iconqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: vqav2
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_vqav2
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: pope
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_pope
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: mathvista
  batch_size: 1
  log_samples: true
  log_samples_suffix: mantis-8b-idefics2_8192_qlora_mathvista
  output_path: "./logs/"
