- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: textvqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_textvqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: ok_vqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_ok_vqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: mmbench
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_mmbench
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: mmmu
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_mmmu
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: chartqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_chartqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: ai2d
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_ai2d
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: mme
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_mme
  output_path: "./logs/"


- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: hallusion_bench
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_hallusion_bench
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: docvqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_docvqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: ocrbench
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_ocrbench
  output_path: "./logs/"
  
- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: gqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_gqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: scienceqa_img
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_scienceqa_img
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: iconqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_iconqa
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: vqav2
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_vqav2
  output_path: "./logs/"

- model: idefics2
  model_args: pretrained=Mantis-VL/mantis-8b-idefics2_8192_qlora
  tasks: pope
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_siglip_llama3_8b_finetune_8192_pope
  output_path: "./logs/"
