- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: ai2d
  batch_size: 1
  log_samples: true
  log_samples_suffix: ai2d
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: mme
  batch_size: 1
  log_samples: true
  log_samples_suffix: mme
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: mmmu
  batch_size: 1
  log_samples: true
  log_samples_suffix: mmmu
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: gqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: gqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: textvqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: textvqa
  output_path: "./logs/"

# - model: mllava
#   model_args: pretrained=MFuyu/llava_bakllava_8192
#   tasks: llava_in_the_wild
#   batch_size: 1
#   log_samples: true
#   log_samples_suffix: llava_in_the_wild
#   output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: vizwiz_vqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: vizwiz_vqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: ok_vqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: ok_vqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: chart_vqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: chart_vqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: hallusion_bench
  batch_size: 1
  log_samples: true
  log_samples_suffix: hallusion_bench
  output_path: "./logs/"


- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: docvqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: docvqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: ocrbench
  batch_size: 1
  log_samples: true
  log_samples_suffix: ocrbench
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: scienceqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: scienceqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: infovqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: infocqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: iconqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: iconqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: mmbench
  batch_size: 1
  log_samples: true
  log_samples_suffix: mmbench
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_bakllava_8192
  tasks: vqav2
  batch_size: 1
  log_samples: true
  log_samples_suffix: vqav2
  output_path: "./logs/"


