# - model: mllava
#   model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
#   tasks: ai2d
#   batch_size: 1
#   log_samples: true
#   log_samples_suffix: llava_1.5_7b_v2_4096_ai2d
#   output_path: "./logs/"

# - model: mllava
#   model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
#   tasks: mme
#   batch_size: 1
#   log_samples: true
#   log_samples_suffix: llava_1.5_7b_v2_4096_mme
#   output_path: "./logs/"

# - model: mllava
#   model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
#   tasks: mmmu
#   batch_size: 1
#   log_samples: true
#   log_samples_suffix: llava_1.5_7b_v2_4096_mmmu
#   output_path: "./logs/"

# - model: mllava
#   model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
#   tasks: scienceqa
#   batch_size: 1
#   log_samples: true
#   log_samples_suffix: llava_1.5_7b_v2_4096_scienceqa
#   output_path: "./logs/"
  
- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: gqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_gqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: textvqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_textvqa
  output_path: "./logs/"

# - model: mllava
#   model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
#   tasks: llava_in_the_wild
#   batch_size: 1
#   log_samples: true
#   log_samples_suffix: llava_1.5_7b_v2_4096_llava_in_the_wild
#   output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: vizwiz_vqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_vizwiz_vqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: ok_vqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_ok_vqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: chart_vqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_chart_vqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: hallusion_bench
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_hallusion_bench
  output_path: "./logs/"


- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: docvqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_docvqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: ocrbench
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_ocrbench
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: scienceqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_scienceqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: infovqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_infocqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: iconqa
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_iconqa
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: mmbench
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_mmbench
  output_path: "./logs/"

- model: mllava
  model_args: pretrained=MFuyu/llava_1.5_7b_v2_4096
  tasks: vqav2
  batch_size: 1
  log_samples: true
  log_samples_suffix: llava_1.5_7b_v2_4096_vqav2
  output_path: "./logs/"

